language: java
jdk:
  - oraclejdk8

os:
  - linux

install:
  - sudo apt-get update -y
  - sudo apt-get upgrade -y
  - sudo apt-get install libboost-all-dev libevent-dev g++ bison libssl-dev -y
  - sudo apt-get install nodejs npm -y
  - sudo apt-get install thrift-compiler -y
  - ./buildApp.sh

script:
  - cd Robots_diagram
  - mvn clean tomcat7:run-war

notifications:
  slack: qreal-web:sT5qgA4qZZ9eyLI0yy2Mp81E
