language: java
jdk:
  - oraclejdk8

os:
  - linux
dist: trusty

before_install:
  #update all repo lists
  - sudo apt-get update -y
  #install curl for tomcat tests
  - sudo apt-get install curl -y
  # get thrift 0.9.3
  - wget "https://www.dropbox.com/s/u4prfzehb94xo9n/thrift"
  - wget "https://www.dropbox.com/s/ydbf9ghsl6lv5dl/libthrift-0.9.3.jar"
  - chmod 755 thrift
  - sudo cp thrift /usr/local/bin/thrift
  - sudo cp libthrift-0.9.3.jar /usr/local/lib
  - wget http://downloads.sourceforge.net/project/checkstyle/checkstyle/7.0/checkstyle-7.0-all.jar


install:
  - mvn install

script:
  #run checkstyle
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml auth-service/src
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml dashboard-service/src
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml editor-service/src
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml db-services/diagram-service/src
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml db-services/robots-service/src
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml db-services/user-service/src

  #run services
  - cd db-services

  - cd diagram-service
  - mvn exec:java &

  - cd ../user-service
  - mvn exec:java &

  - cd ../robots-service
  - mvn exec:java &

  - cd ../../auth-service
  - mvn tomcat7:run-war &

  - cd  ../dashboard-service
  - mvn tomcat7:run-war &

  - cd ../editor-service
  - mvn tomcat7:run-war &

  - ../Travis/callTomcat.sh

notifications:
  slack: qreal-web:sT5qgA4qZZ9eyLI0yy2Mp81E
