language: java
jdk:
  - oraclejdk8

os:
  - linux
dist: trusty

before_install:
  - sudo apt-get update -y
  # - sudo apt-get upgrade -y
  #install 0.9.3 thrift version
  - mkdir ThriftInstall
  - cd ThriftInstall
  - wget http://apache-mirror.rbc.ru/pub/apache/thrift/0.9.3/thrift-0.9.3.tar.gz
  - tar -xf thrift-0.9.3.tar.gz 
  - cd thrift-0.9.3
  - ./configure
  - make
  - sudo make install
  - sudo ln -s /usr/local/bin/thrift /usr/bin/thriftD
  - cd ../..
  #!install 0.9.3 thrift version
  - sudo apt-get install libboost-all-dev libevent-dev g++ bison libssl-dev -y
  - sudo apt-get install nodejs npm -y
  - sudo apt-get install curl -y

install:
  - ./buildApp.sh

script:
  - cd Robots_diagram
  - mvn clean tomcat7:run-war &
  - ../Travis/callTomcat.sh

notifications:
  slack: qreal-web:sT5qgA4qZZ9eyLI0yy2Mp81E
